name: Build and Push Docker Image to GitHub Registry

on:
  push:
    branches:
      - main  # or any other branch you'd like to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.10.0
        with:
          context: .
          push: true
          tags: ghcr.io/randycrowley/${{ github.ref_name }}

